import { z } from "zod";
import type { FabricRole } from "@/lib/fabric/config";

const id = z.string().trim().min(1).max(100).regex(/^[a-zA-Z0-9._:-]+$/);
const hash = z.string().trim().regex(/^[a-fA-F0-9]{64}$/).transform((value) => value.toLowerCase());
const date = z.string().regex(/^\d{4}-\d{2}-\d{2}$/);
const money = z.number().int().positive().safe();

export const workflowCommandSchema = z.discriminatedUnion("operation", [
  z.object({
    operation: z.literal("createPolicyPackage"),
    id,
    name: z.string().trim().min(1).max(120),
    description: z.string().trim().max(1_000),
    premiumMinor: money,
    coverageLimitMinor: money,
    termsHash: hash,
  }),
  z.object({ operation: z.literal("publishPolicyPackage"), id }),
  z.object({ operation: z.literal("retirePolicyPackage"), id }),
  z.object({ operation: z.literal("createBenefitPlan"), id, packageId: id, deathBenefitMinor: z.number().int().nonnegative().safe(), surrenderBenefitMinor: z.number().int().nonnegative().safe(), maturityBenefitMinor: z.number().int().nonnegative().safe(), rulesHash: hash }),
  z.object({ operation: z.literal("publishBenefitPlan"), id }),
  z.object({ operation: z.literal("retireBenefitPlan"), id }),
  z.object({
    operation: z.literal("issuePolicy"),
    id,
    packageId: id,
    policyholderId: id,
    startDate: date,
    endDate: date,
  }),
  z.object({ operation: z.literal("acquirePolicy"), id, packageId: id, startDate: date, endDate: date }),
  z.object({ operation: z.literal("advancePolicyLifecycle"), id, asOfDate: date }),
  z.object({ operation: z.literal("cancelPolicy"), id, reasonHash: hash }),
  z.object({ operation: z.literal("cancelPolicyAsInsurer"), id, reasonHash: hash }),
  z.object({ operation: z.literal("renewPolicy"), newId: id, existingId: id, newEndDate: date }),
  z.object({ operation: z.literal("registerBankAccountReference"), id, ownerId: id, accountTokenHash: hash }),
  z.object({ operation: z.literal("requestBankMandate"), id, policyId: id, accountReferenceId: id, expiryDate: date }),
  z.object({ operation: z.literal("reviewBankMandate"), id, outcome: z.enum(["APPROVE", "REJECT"]), decisionHash: hash }),
  z.object({ operation: z.literal("cancelBankMandate"), id }),
  z.object({ operation: z.literal("expireBankMandate"), id, asOfDate: date }),
  z.object({ operation: z.literal("recordPremiumPayment"), id, policyId: id, mandateId: id, periodStartDate: date, periodEndDate: date, amountMinor: money, externalReferenceHash: hash, method: z.enum(["OTP", "AUTODEBIT"]) }),
  z.object({ operation: z.literal("recordPremiumAdjustment"), id, paymentId: id, amountMinor: money, externalReferenceHash: hash, reasonHash: hash }),
  z.object({ operation: z.literal("queuePremiumCollection"), id, mandateId: id, dueDate: date }),
  z.object({ operation: z.literal("completePremiumCollection"), collectionId: id, paymentId: id, periodEndDate: date, externalReferenceHash: hash }),
  z.object({ operation: z.literal("failPremiumCollection"), collectionId: id, failureHash: hash }),
  z.object({ operation: z.literal("setBeneficiaries"), policyId: id, allocationsJson: z.string().trim().min(2).max(2_000) }),
  z.object({ operation: z.literal("submitBenefitRequest"), id, policyId: id, benefitType: z.enum(["DEATH", "SURRENDER", "MATURITY"]), eventDate: date, evidenceHash: hash }),
  z.object({ operation: z.literal("decideBenefitRequest"), id, outcome: z.enum(["APPROVE", "REJECT"]), decisionHash: hash }),
  z.object({ operation: z.literal("markBenefitPaymentReady"), id, fundingReferenceHash: hash }),
  z.object({ operation: z.literal("confirmBenefitPayment"), id, bankReferenceHash: hash }),
  z.object({
    operation: z.literal("submitClaim"),
    id,
    policyId: id,
    amountMinor: money,
    incidentDate: date,
    descriptionHash: hash,
  }),
  z.object({
    operation: z.literal("verifyClaim"),
    claimId: id,
    verificationId: id,
    outcome: z.enum(["VERIFIED", "INVALID"]),
    clinicalReferenceHash: hash,
  }),
  z.object({ operation: z.literal("openClaimReview"), claimId: id, reviewId: id, assignedAuditorIdsJson: z.string().trim().min(2).max(1_000), approvalThreshold: z.number().int().positive().max(9), rejectionThreshold: z.number().int().positive().max(9), deadline: z.string().datetime({ offset: true }) }),
  z.object({ operation: z.literal("publishOracleRegistrySnapshot"), id, version: z.number().int().positive(), rootHash: hash, rulesVersion: id, rulesHash: hash, recordCount: z.number().int().positive() }),
  z.object({ operation: z.literal("requestOracleVerification"), requestId: id, claimId: id, snapshotId: id, modelVersion: id, modelHash: hash, assignedOracleIdsJson: z.string().trim().min(2).max(500), commitDeadline: z.string().datetime({ offset: true }), revealDeadline: z.string().datetime({ offset: true }) }),
  z.object({ operation: z.literal("finalizeOracleTimeout"), requestId: id }),
  z.object({ operation: z.literal("routeOracleFailureToReview"), requestId: id, reviewId: id, assignedAuditorIdsJson: z.string().trim().min(2).max(1_000), approvalThreshold: z.number().int().positive().max(9), rejectionThreshold: z.number().int().positive().max(9), deadline: z.string().datetime({ offset: true }) }),
  z.object({ operation: z.literal("submitClaimAppeal"), appealId: id, claimId: id, reasonHash: hash, evidenceHash: z.union([hash, z.literal("")]).default("") }),
  z.object({
    operation: z.literal("grantEvidenceAccess"),
    id,
    evidenceId: id,
    granteeMsp: z.enum(["InsurerMSP", "HospitalMSP", "AuditorMSP"]),
    granteeRole: z.enum(["insurerAdmin", "hospitalOfficer", "auditor"]),
    granteeSubject: z.string().trim().min(1).max(128),
    purpose: z.enum(["DOWNLOAD", "VERIFY", "AUDIT"]),
    expiresAt: z.string().datetime({ offset: true }),
    maxAccesses: z.number().int().min(1).max(100),
  }),
  z.object({ operation: z.literal("revokeEvidenceAccess"), grantId: id }),
  z.object({ operation: z.literal("openAppealReview"), appealId: id, reviewId: id, assignedAuditorIdsJson: z.string().trim().min(2).max(1_000), approvalThreshold: z.number().int().positive().max(9), rejectionThreshold: z.number().int().positive().max(9), deadline: z.string().datetime({ offset: true }) }),
  z.object({ operation: z.literal("finalizeExpiredReview"), reviewId: id }),
  z.object({ operation: z.literal("assessClaimFraud"), assessmentId: id, claimId: id }),
  z.object({
    operation: z.literal("recordAuditorDecision"),
    reviewId: id,
    decisionId: id,
    outcome: z.enum(["APPROVE", "REJECT"]),
    reasonHash: hash,
  }),
  z.object({ operation: z.literal("authorizeSettlement"), settlementId: id, claimId: id }),
  z.object({ operation: z.literal("confirmSettlement"), settlementId: id, bankReferenceHash: hash }),
]);

export type WorkflowCommand = z.infer<typeof workflowCommandSchema>;
export type WorkflowOperation = WorkflowCommand["operation"];

export const requiredRoleByOperation = {
  createPolicyPackage: "insurerAdmin",
  publishPolicyPackage: "insurerAdmin",
  retirePolicyPackage: "insurerAdmin",
  createBenefitPlan: "insurerAdmin",
  publishBenefitPlan: "insurerAdmin",
  retireBenefitPlan: "insurerAdmin",
  issuePolicy: "insurerAdmin",
  acquirePolicy: "policyholder",
  advancePolicyLifecycle: "insurerAdmin",
  cancelPolicy: "policyholder",
  cancelPolicyAsInsurer: "insurerAdmin",
  renewPolicy: "policyholder",
  registerBankAccountReference: "bankOfficer",
  requestBankMandate: "policyholder",
  reviewBankMandate: "bankOfficer",
  cancelBankMandate: "policyholder",
  expireBankMandate: "bankOfficer",
  recordPremiumPayment: "bankOfficer",
  recordPremiumAdjustment: "bankOfficer",
  queuePremiumCollection: "insurerAdmin",
  completePremiumCollection: "bankOfficer",
  failPremiumCollection: "bankOfficer",
  setBeneficiaries: "policyholder",
  submitBenefitRequest: "policyholder",
  decideBenefitRequest: "insurerAdmin",
  markBenefitPaymentReady: "insurerAdmin",
  confirmBenefitPayment: "bankOfficer",
  submitClaim: "policyholder",
  verifyClaim: "hospitalOfficer",
  openClaimReview: "insurerAdmin",
  publishOracleRegistrySnapshot: "insurerAdmin",
  requestOracleVerification: "insurerAdmin",
  finalizeOracleTimeout: "insurerAdmin",
  routeOracleFailureToReview: "insurerAdmin",
  submitClaimAppeal: "policyholder",
  grantEvidenceAccess: "policyholder",
  revokeEvidenceAccess: "policyholder",
  openAppealReview: "insurerAdmin",
  finalizeExpiredReview: "insurerAdmin",
  assessClaimFraud: "insurerAdmin",
  recordAuditorDecision: "auditor",
  authorizeSettlement: "insurerAdmin",
  confirmSettlement: "bankOfficer",
} as const satisfies Record<WorkflowOperation, FabricRole>;

export function canExecute(role: FabricRole, operation: WorkflowOperation) {
  return requiredRoleByOperation[operation] === role;
}
