import { z } from "zod";
import type { FabricRole } from "@/lib/fabric/config";

const id = z.string().trim().min(1).max(100).regex(/^[a-zA-Z0-9._:-]+$/);
const hash = z.string().trim().regex(/^[a-fA-F0-9]{64}$/).transform((value) => value.toLowerCase());
const date = z.string().regex(/^\d{4}-\d{2}-\d{2}$/);
const money = z.number().int().positive().safe();

export const workflowCommandSchema = z.discriminatedUnion("operation", [
  z.object({
    operation: z.literal("createPartnerAgreement"), id,
    partnerType: z.enum(["HOSPITAL", "BANK"]), partnerId: id,
    name: z.string().trim().min(1).max(160), location: z.string().trim().max(160),
    tier: z.string().trim().max(80), accessScope: z.string().trim().min(1).max(500),
    effectiveDate: date, expiryDate: date,
  }),
  z.object({ operation: z.literal("setPartnerAgreementStatus"), id, status: z.enum(["ACTIVE", "SUSPENDED", "ENDED"]) }),
  z.object({ operation: z.literal("configurePolicyPackagePartners"), id, hospitalIdsJson: z.string().trim().min(2).max(2_000), bankIdsJson: z.string().trim().min(2).max(2_000) }),
  z.object({
    operation: z.literal("createPolicyPackage"),
    id,
    name: z.string().trim().min(1).max(120),
    description: z.string().trim().max(1_000),
    premiumMinor: money,
    coverageLimitMinor: money,
    termsHash: hash,
  }),
  z.object({ operation: z.literal("publishPolicyPackage"), id }),
  z.object({ operation: z.literal("retirePolicyPackage"), id }),
  z.object({ operation: z.literal("createBenefitPlan"), id, packageId: id, deathBenefitMinor: z.number().int().nonnegative().safe(), surrenderBenefitMinor: z.number().int().nonnegative().safe(), maturityBenefitMinor: z.number().int().nonnegative().safe(), rulesHash: hash }),
  z.object({ operation: z.literal("publishBenefitPlan"), id }),
  z.object({ operation: z.literal("retireBenefitPlan"), id }),
  z.object({
    operation: z.literal("issuePolicy"),
    id,
    packageId: id,
    policyholderId: id,
    startDate: date,
    endDate: date,
  }),
  z.object({ operation: z.literal("acquirePolicy"), id, packageId: id, startDate: date, endDate: date }),
  z.object({ operation: z.literal("advancePolicyLifecycle"), id, asOfDate: date }),
  z.object({ operation: z.literal("cancelPolicy"), id, reasonHash: hash }),
  z.object({ operation: z.literal("cancelPolicyAsInsurer"), id, reasonHash: hash }),
  z.object({ operation: z.literal("renewPolicy"), newId: id, existingId: id, newEndDate: date }),
  z.object({ operation: z.literal("openBankAccount"), id, bankId: id, ownerId: id, accountType: z.enum(["CUSTOMER", "INSURER"]), accountTokenHash: hash, openingBalanceMinor: z.number().int().nonnegative().safe() }),
  z.object({ operation: z.literal("adjustBankAccountBalance"), transferId: id, accountId: id, direction: z.enum(["CREDIT", "DEBIT"]), amountMinor: money, externalReferenceHash: hash }),
  z.object({ operation: z.literal("requestBankMandate"), id, policyId: id, accountReferenceId: id, expiryDate: date }),
  z.object({ operation: z.literal("reviewBankMandate"), id, outcome: z.enum(["APPROVE", "REJECT"]), decisionHash: hash }),
  z.object({ operation: z.literal("cancelBankMandate"), id }),
  z.object({ operation: z.literal("expireBankMandate"), id, asOfDate: date }),
  z.object({ operation: z.literal("recordPremiumAdjustment"), id, paymentId: id, amountMinor: money, externalReferenceHash: hash, reasonHash: hash }),
  z.object({ operation: z.literal("queuePremiumCollection"), id, mandateId: id, dueDate: date }),
  z.object({ operation: z.literal("processPremiumCollection"), collectionId: id, paymentId: id, transferId: id, destinationAccountId: id, periodEndDate: date, externalReferenceHash: hash }),
  z.object({ operation: z.literal("setBeneficiaries"), policyId: id, allocationsJson: z.string().trim().min(2).max(2_000) }),
  z.object({ operation: z.literal("submitBenefitRequest"), id, policyId: id, benefitType: z.enum(["DEATH", "SURRENDER", "MATURITY"]), eventDate: date, evidenceHash: hash }),
  z.object({ operation: z.literal("decideBenefitRequest"), id, outcome: z.enum(["APPROVE", "REJECT"]), decisionHash: hash }),
  z.object({ operation: z.literal("markBenefitPaymentReady"), id, fundingReferenceHash: hash }),
  z.object({ operation: z.literal("confirmBenefitPayment"), id, bankReferenceHash: hash }),
  z.object({
    operation: z.literal("createHospitalInvoice"), id,
    patientReferenceHash: hash, invoiceReferenceHash: hash, treatmentHash: hash,
    amountMinor: money, admissionDate: date, dischargeDate: date,
    status: z.enum(["DRAFT", "FINALIZED"]),
  }),
  z.object({
    operation: z.literal("updateHospitalInvoice"), id,
    patientReferenceHash: hash, invoiceReferenceHash: hash, treatmentHash: hash,
    amountMinor: money, admissionDate: date, dischargeDate: date,
    status: z.enum(["DRAFT", "FINALIZED", "VOID"]),
  }),
  z.object({
    operation: z.literal("submitClaim"),
    id,
    policyId: id,
    hospitalId: id,
    hospitalInvoiceId: id,
    amountMinor: money,
    incidentDate: date,
    descriptionHash: hash,
  }),
  z.object({ operation: z.literal("crossCheckClaimInvoice"), claimId: id, verificationId: id }),
  z.object({ operation: z.literal("openClaimReview"), claimId: id, reviewId: id, assignedAuditorIdsJson: z.string().trim().min(2).max(1_000), approvalThreshold: z.number().int().positive().max(9), rejectionThreshold: z.number().int().positive().max(9), deadline: z.string().datetime({ offset: true }) }),
  z.object({ operation: z.literal("publishOracleRegistrySnapshot"), id, version: z.number().int().positive(), rootHash: hash, rulesVersion: id, rulesHash: hash, recordCount: z.number().int().positive() }),
  z.object({ operation: z.literal("requestOracleVerification"), requestId: id, claimId: id, snapshotId: id, modelVersion: id, modelHash: hash, assignedOracleIdsJson: z.string().trim().min(2).max(500), commitDeadline: z.string().datetime({ offset: true }), revealDeadline: z.string().datetime({ offset: true }) }),
  z.object({ operation: z.literal("finalizeOracleTimeout"), requestId: id }),
  z.object({ operation: z.literal("routeOracleFailureToReview"), requestId: id, reviewId: id, assignedAuditorIdsJson: z.string().trim().min(2).max(1_000), approvalThreshold: z.number().int().positive().max(9), rejectionThreshold: z.number().int().positive().max(9), deadline: z.string().datetime({ offset: true }) }),
  z.object({
    operation: z.literal("submitClaimAppeal"), appealId: id, claimId: id,
    reasonCategory: z.enum(["DOCUMENT_ERROR", "CLINICAL_CORRECTION", "AMOUNT_CORRECTION", "OTHER"]),
    reasonHash: hash, descriptionHash: hash,
    evidenceHash: z.union([hash, z.literal("")]).default(""),
    proposedHospitalId: z.union([id, z.literal("")]).default(""),
    proposedAmountMinor: z.number().int().nonnegative().safe().default(0),
    proposedIncidentDate: z.union([date, z.literal("")]).default(""),
    proposedDescriptionHash: z.union([hash, z.literal("")]).default(""),
    proposedClinicalReferenceHash: hash,
  }),
  z.object({
    operation: z.literal("grantEvidenceAccess"),
    id,
    evidenceId: id,
    granteeMsp: z.enum(["InsurerMSP", "HospitalMSP", "AuditorMSP"]),
    granteeRole: z.enum(["insurerAdmin", "hospitalOfficer", "auditor"]),
    granteeSubject: z.string().trim().min(1).max(128),
    purpose: z.enum(["DOWNLOAD", "VERIFY", "AUDIT"]),
    expiresAt: z.string().datetime({ offset: true }),
    maxAccesses: z.number().int().min(1).max(100),
  }),
  z.object({ operation: z.literal("revokeEvidenceAccess"), grantId: id }),
  z.object({ operation: z.literal("openAppealReview"), appealId: id, reviewId: id, assignedAuditorIdsJson: z.string().trim().min(2).max(1_000), approvalThreshold: z.number().int().positive().max(9), rejectionThreshold: z.number().int().positive().max(9), deadline: z.string().datetime({ offset: true }) }),
  z.object({ operation: z.literal("finalizeExpiredReview"), reviewId: id }),
  z.object({ operation: z.literal("assessClaimFraud"), assessmentId: id, claimId: id }),
  z.object({
    operation: z.literal("recordAuditorDecision"),
    reviewId: id,
    decisionId: id,
    outcome: z.enum(["APPROVE", "REJECT"]),
    reasonHash: hash,
  }),
  z.object({ operation: z.literal("authorizeSettlement"), settlementId: id, claimId: id }),
  z.object({ operation: z.literal("confirmSettlement"), settlementId: id, bankReferenceHash: hash }),
]);

export type WorkflowCommand = z.infer<typeof workflowCommandSchema>;
export type WorkflowOperation = WorkflowCommand["operation"];

export const requiredRoleByOperation = {
  createPartnerAgreement: "insurerAdmin",
  setPartnerAgreementStatus: "insurerAdmin",
  configurePolicyPackagePartners: "insurerAdmin",
  createPolicyPackage: "insurerAdmin",
  publishPolicyPackage: "insurerAdmin",
  retirePolicyPackage: "insurerAdmin",
  createBenefitPlan: "insurerAdmin",
  publishBenefitPlan: "insurerAdmin",
  retireBenefitPlan: "insurerAdmin",
  issuePolicy: "insurerAdmin",
  acquirePolicy: "policyholder",
  advancePolicyLifecycle: "insurerAdmin",
  cancelPolicy: "policyholder",
  cancelPolicyAsInsurer: "insurerAdmin",
  renewPolicy: "policyholder",
  openBankAccount: "bankOfficer",
  adjustBankAccountBalance: "bankOfficer",
  requestBankMandate: "policyholder",
  reviewBankMandate: "bankOfficer",
  cancelBankMandate: "policyholder",
  expireBankMandate: "bankOfficer",
  recordPremiumAdjustment: "bankOfficer",
  queuePremiumCollection: "insurerAdmin",
  processPremiumCollection: "bankOfficer",
  setBeneficiaries: "policyholder",
  submitBenefitRequest: "policyholder",
  decideBenefitRequest: "insurerAdmin",
  markBenefitPaymentReady: "insurerAdmin",
  confirmBenefitPayment: "bankOfficer",
  createHospitalInvoice: "hospitalOfficer",
  updateHospitalInvoice: "hospitalOfficer",
  submitClaim: "policyholder",
  crossCheckClaimInvoice: "insurerAdmin",
  openClaimReview: "insurerAdmin",
  publishOracleRegistrySnapshot: "insurerAdmin",
  requestOracleVerification: "insurerAdmin",
  finalizeOracleTimeout: "insurerAdmin",
  routeOracleFailureToReview: "insurerAdmin",
  submitClaimAppeal: "policyholder",
  grantEvidenceAccess: "policyholder",
  revokeEvidenceAccess: "policyholder",
  openAppealReview: "insurerAdmin",
  finalizeExpiredReview: "insurerAdmin",
  assessClaimFraud: "insurerAdmin",
  recordAuditorDecision: "auditor",
  authorizeSettlement: "insurerAdmin",
  confirmSettlement: "bankOfficer",
} as const satisfies Record<WorkflowOperation, FabricRole>;

export function canExecute(role: FabricRole, operation: WorkflowOperation) {
  return requiredRoleByOperation[operation] === role;
}
